### ISSUE TITLE
Hidden failure when `sourceField` undefined or null on source document

### ISSUE THREAD

**Issue by kylewelsby** [thetre97/gridsome-plugin-image-cdn#20]
## Configuration:
```javascript
module.exports = {
  plugins: [
    {
      use: "@gridsome/source-filesystem",
      options: {
        typeName: "Track",
        baseDir: "./content",
        path: "./artists/**/tracks/*.md"
      }
    },
    {
      use: 'gridsome-plugin-image-cdn',
      options: {
        cdn: {
          baseUrl: "https://example.com/cdn/image",
          preset: 'cloudinary',
          imagePrefix: '/'
        },
        types: [
          {
            typeName: 'Track',
            sourceField: 'artwork'
          }
        ]
      }
    }
  ]
};
```

## Observed error message:

```
An error occurred while executing page-query for src/templates/Track.vue

Error: Cannot read property 'replace' of undefined

GraphQL request:74:5
73 |     title
74 |     artwork
   |     ^
75 |     artist {
    at throwError (./node_modules/gridsome/lib/app/build/executeQueries.js:23:13)
    at pMap.concurrency (./node_modules/gridsome/lib/app/build/executeQueries.js:62:9)
error Command failed with exit code 1.

```

**Comment by kylewelsby** [comment]
It is my intent to fix this bug, or find a workaround and document the fix here.

**Comment by kylewelsby** [comment]
Here is the work-around, not ideal as it doesn't allow a `null` for the field.

```javascript
gridsome.server.js

module.exports = function(api) {
  api.loadSource(({ getCollection } => {
      const tracks = getCollection("Track");
      tracks.data().forEach((track) => {
        if(!track.artwork) {
          track.artwork = '' // empty string
        }
      })
  })
}
```

**Comment by kylewelsby** [comment]
Ideally, there should be a fix [around `sourceUrl` resolver](https://github.com/thetre97/gridsome-plugin-image-cdn/blob/96172b9b150385cb5b0e6fc38984c668d88d629a/gridsome.server.js#L26-L35) to check the field exists on the parent before trying to transform the field to a URL. 


```javascript
            resolve: (parent, args, ctx, info) => {
              // Get the sourceUrl, using either the sourceField, or the path key in case of an alias.
              const field = parent[ sourceField ] || parent[ info.path.key ]
              if (!field) return field // <--- return the null or undefined field
              const sourceUrl = field.replace(site.baseUrl, '')

              // If no transformer is configure, ignore it and return the original url
              if (!transformer) return sourceUrl

              // Otherwise handoff to the transformer
              return transformer({ cdn, sourceUrl, args })
            }
```

Not sure if to check for blank strings too,  What would you suggest?

**Comment by travis-r6s** [comment]
The above solution looks good to me - it will catch empty strings as well (`!'' = true`).

Thanks!
